spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: walmart
      uri: mongodb://127.0.0.1:27017/walmart
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
url:
  gr: 
    context: https://super-qa.walmart.com.mx
    login: /api/rest/model/atg/userprofiling/ProfileActor/login
